# Generated by Django 2.1.5 on 2019-06-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeerCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brewer', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField()),
                ('rating', models.CharField(max_length=10)),
                ('servingType', models.CharField(max_length=200)),
                ('flavourDesc', models.TextField()),
                ('upVotes', models.IntegerField()),
                ('downVotes', models.IntegerField()),
            ],
        ),
    ]
